version: '3.8'

services:

  odoo:
    image: alphaticks/odoo:12
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - odoodata:/var/lib/odoo
    configs:
      - source: odoo_config
        target: /etc/odoo/odoo.conf
    environment:
      - HOST=postgres

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
       - postgresdb:/var/lib/postgresql/data

configs:
   odoo_config:
      file: ./configs/odoo.conf

volumes:
  odoodata:
  postgresdb:
