version: '3.8'

services:

  odoo:
    image: alphaticks/odoo:12
    depends_on:
      - postgres
    ports:
      - "8072:8072"
    volumes:
      - odoodata:/var/lib/odoo
    configs:
      - source: odoo_config
        target: /etc/odoo/odoo.conf
    environment:
      - HOST=postgres

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
       - postgresdb:/var/lib/postgresql/data

  proxy:
    image: nginx
    configs:
       - source: nginx_config
         target: /etc/nginx/nginx.conf
    ports:
       - "8069:8069"
         
configs:
   odoo_config:
      file: ./configs/odoo.conf
   nginx_config:
      file: ./configs/nginx.conf

volumes:
  odoodata:
  postgresdb:
